######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 23 15:59:58 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += glidenote.h main.moc
SOURCES += main.cpp
CONFIG  += qxt
QXT     += core gui
